using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WarhammerArmyAssembler
{
    class Enemy : Unit
    {
        public static int MaxIDindex = -10;

        private static Dictionary<string, List<Enemy>> GetEnemiesDictionary()
        {
            return  new Dictionary<string, List<Enemy>>
            {
                ["Lords"] = new List<Enemy>(EnemiesLords),
                ["Heroes"] = new List<Enemy>(EnemiesHeroes),
                ["Core Units"] = new List<Enemy>(EnemiesCoreUnits),
                ["Special Units"] = new List<Enemy>(EnemiesSpecialUnits),
                ["Rare Units"] = new List<Enemy>(EnemiesRareUnits),
                ["Monsters"] = new List<Enemy>(EnemiesMonsters),
            };
        }

        public static Enemy GetByName(string enemyName)
        {
            foreach (List<Enemy> enemyList in new List<List<Enemy>>
            {
                EnemiesMonsters, EnemiesHeroes, EnemiesLords,
                EnemiesCoreUnits, EnemiesSpecialUnits, EnemiesRareUnits,
            })
                foreach (Enemy enemy in enemyList)
                    if (enemy.TestListName == enemyName)
                        return enemy.SetID();

            return null;
        }

        private Enemy SetID()
        {
            MaxIDindex -= 1;

            this.ID = MaxIDindex;

            return this;
        }

        public static List<string> GetEnemiesGroups()
        {
            return GetEnemiesDictionary().Keys.ToList<string>();
        }

        public static List<Enemy> GetEnemiesByGroup(string groupName)
        {
            return GetEnemiesDictionary()[groupName];
        }

        private static List<Enemy> EnemiesMonsters = new List<Enemy>
        {
            new Enemy
            {
                Name = "Troll",
                TestListName = "Troll (Orcs&Goblins)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(1),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(1),
                Attacks = new MainParam(3),
                Leadership = new MainParam(4),
                Fear = true,
                Regeneration = true,
                Stupidity = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Gyrobomber",
                TestListName = "Gyrobomber (Dwarfs)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(1),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(2),
                Attacks = new MainParam(2),
                Leadership = new MainParam(9),
                Armour = new MainParam(4),
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Ancient Kroxigor",
                TestListName = "Ancient Kroxigor (Lizardmen)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(1),
                Strength = new MainParam(7),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(1),
                Attacks = new MainParam(4),
                Leadership = new MainParam(7),
                Fear = true,
                ColdBlooded = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Tomb Scorpion",
                TestListName = "Tomb Scorpion (Tomb Kings)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(7),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(3),
                Attacks = new MainParam(4),
                Leadership = new MainParam(8),
                Undead = true,
                KillingBlow = true,
                PoisonAttack = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Hippogryph",
                TestListName = "Hippogryph (Bretonnia)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(8),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(4),
                Attacks = new MainParam(4),
                Leadership = new MainParam(8),
                Terror = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Griffon",
                TestListName = "Griffon (The Empire)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(5),
                Attacks = new MainParam(4),
                Leadership = new MainParam(7),
                Terror = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Manticore",
                TestListName = "Manticore (Chaos)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(5),
                Attacks = new MainParam(4),
                Leadership = new MainParam(5),
                Terror = true,
                KillingBlow = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Varghulf",
                TestListName = "Varghulf (Vampire)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(8),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(2),
                Attacks = new MainParam(5),
                Leadership = new MainParam(4),
                Terror = true,
                Undead = true,
                Regeneration = true,
                Hate = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "War Hydra",
                TestListName = "War Hydra (Dark Elves)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(6),
                Initiative = new MainParam(2),
                Attacks = new MainParam(5),
                Leadership = new MainParam(6),
                Armour = new MainParam(4),
                Terror = true,
                LargeBase = true,

                Mount = new Enemy
                {
                    Name = "Apparentice",
                    Type = UnitType.Mount,
                    Size = 2,
                    Movement = new MainParam(5),
                    WeaponSkill = new MainParam(4),
                    BallisticSkill = new MainParam(4),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(2),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(2),
                    Leadership = new MainParam(8),
                    NoKollingBlow = true,
                }
            },

            new Enemy
            {
                Name = "Dragon Ogre",
                TestListName = "Dragon Ogre Shaggoth (Beastmen)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(7),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(6),
                Initiative = new MainParam(4),
                Attacks = new MainParam(5),
                Leadership = new MainParam(9),
                Armour = new MainParam(4),
                Terror = true,
                ImmuneToPsychology = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Stegadon",
                TestListName = "Stegadon (Lizardmen)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(6),
                Wounds = new MainParam(5),
                Initiative = new MainParam(2),
                Attacks = new MainParam(4),
                Leadership = new MainParam(5),
                Armour = new MainParam(4),
                LargeBase = true,
                ColdBlooded = true,
                Terror = true,
                Stubborn = true,
                ImmuneToPsychology = true,

                Mount = new Enemy
                {
                    Name = "Skink Crew",
                    Type = UnitType.Mount,
                    Size = 5,
                    Movement = new MainParam(6),
                    WeaponSkill = new MainParam(2),
                    BallisticSkill = new MainParam(3),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(2),
                    Wounds = new MainParam(4),
                    Initiative = new MainParam(4),
                    Attacks = new MainParam(4),
                    Leadership = new MainParam(5),
                    Armour = new MainParam(4),
                    ColdBlooded = true,
                    PoisonAttack = true,
                    NoKollingBlow = true,
                }
            },

            new Enemy
            {
                Name = "Treeman",
                TestListName = "Treeman (Wood Elves)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(6),
                Toughness = new MainParam(6),
                Wounds = new MainParam(6),
                Initiative = new MainParam(2),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                Armour = new MainParam(3),
                Terror = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Hell Pit Abomination",
                TestListName = "Hell Pit Abomination (Skaven)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(0),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(1),
                Strength = new MainParam(6),
                Toughness = new MainParam(5),
                Wounds = new MainParam(6),
                Initiative = new MainParam(4),
                Attacks = new MainParam(0),
                Leadership = new MainParam(8),
                Regeneration = true,
                Terror = true,
                Stubborn = true,
                LargeBase = true,
                HellPitAbomination = true,
            },

            new Enemy
            {
                Name = "Necrosphinx",
                TestListName = "Necrosphinx (Tomb Kings)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(8),
                Wounds = new MainParam(5),
                Initiative = new MainParam(1),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                Armour = new MainParam(3),
                Terror = true,
                LargeBase = true,
                HeroicKillingBlow = true,
                Undead = true,
            },

            new Enemy
            {
                Name = "Star Dragon",
                TestListName = "Star Dragon (High Elves)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(7),
                Toughness = new MainParam(6),
                Wounds = new MainParam(7),
                Initiative = new MainParam(2),
                Attacks = new MainParam(6),
                Leadership = new MainParam(9),
                Armour = new MainParam(3),
                Terror = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Steam Tank",
                TestListName = "Steam Tank (Empire)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(0),
                WeaponSkill = new MainParam(0),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(6),
                Toughness = new MainParam(6),
                Wounds = new MainParam(10),
                Initiative = new MainParam(0),
                Attacks = new MainParam(0),
                Leadership = new MainParam(10),
                Armour = new MainParam(1),
                Unbreakable = true,
                Terror = true,
                LargeBase = true,
                SteamTank = true,
            },
        };

        private static List<Enemy> EnemiesCoreUnits = new List<Enemy>
        {
            new Enemy
            {
                Name = "Clanrat Slaves",
                TestListName = "20 Clanrat Slaves (Skaven)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(2),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(4),
                Attacks = new MainParam(1),
                Leadership = new MainParam(2),
                StrengthInNumbers = true,
            },

            new Enemy
            {
                Name = "Men-at-arms",
                TestListName = "20 Men-at-arms (Bretonnia)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(2),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(5),
                Armour = new MainParam(5),
            },

            new Enemy
            {
                Name = "Empire swordmens",
                TestListName = "20 Empire swordmens (Empire)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(7),
                Armour = new MainParam(6),
            },

            new Enemy
            {
                Name = "Orc boys",
                TestListName = "20 Orc Boys (Orcs&Goblins)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(7),
                Armour = new MainParam(5),
            },

            new Enemy
            {
                Name = "Skeleton Warriors",
                TestListName = "20 Skeleton Warriors (Tomb Kings)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(2),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(5),
                Armour = new MainParam(5),
                Undead = true,
            },

            new Enemy
            {
                Name = "Lothern Sea Guard",
                TestListName = "20 Lothern Sea Guard (High Elves)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(6),
                HitFirst = true,
            },

            new Enemy
            {
                Name = "Crypt Ghouls",
                TestListName = "20 Crypt Ghouls (Vampire Counts)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(3),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(2),
                Leadership = new MainParam(5),
                Undead = true,
                PoisonAttack = true,
            },

            new Enemy
            {
                Name = "Back Ark Corsairs",
                TestListName = "20 Back Ark Corsairs (Dark Elves)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(5),
                Hate = true,
            },

            new Enemy
            {
                Name = "Dryads",
                TestListName = "20 Dryads (Wood Elves)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(6),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Fear = true,
            },

            new Enemy
            {
                Name = "Bestigor",
                TestListName = "20 Bestigor (Beastmen)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(6),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(7),
                Armour = new MainParam(5),
                HitLast = true,
            },

            new Enemy
            {
                Name = "Knights of the Realms",
                TestListName = "8 Knights of the Realms (Bretonnia)",
                Type = UnitType.Core,
                Size = 8,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(2),
                Lance = true,

                Mount = new Enemy
                {
                    Name = "Warhorse",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                }
            },

            new Enemy
            {
                Name = "Longbeards",
                TestListName = "20 Longbeards (Dwarfs)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(3),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(9),
                Armour = new MainParam(4),
                ImmuneToPsychology = true
            },

            new Enemy
            {
                Name = "Temple Guard",
                TestListName = "20 Temple Guard (Lizardmen)",
                Type = UnitType.Core,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(4),
                ColdBlooded = true
            },

            new Enemy
            {
                Name = "Chosen Knights of Chaos",
                TestListName = "8 Chosen Knights (Chaos)",
                Type = UnitType.Core,
                Size = 8,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(1),

                Mount = new Enemy
                {
                    Name = "Chaos Steed",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                }
            },
        };

        private static List<Enemy> EnemiesSpecialUnits = new List<Enemy>
        {
            new Enemy
            {
                Name = "Tree Kin",
                TestListName = "5 Tree Kin (Wood Elves)",
                Type = UnitType.Special,
                Size = 5,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(4),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(3),
                Attacks = new MainParam(3),
                Leadership = new MainParam(8),
                Armour = new MainParam(4),
                Fear = true,
            },

            new Enemy
            {
                Name = "Pegasus Knights",
                TestListName = "8 Pegasus Knights (Bretonnia)",
                Type = UnitType.Special,
                Size = 8,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(4),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(3),
                Lance = true,

                Mount = new Enemy
                {
                    Name = "Boar",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(4),
                    Attacks = new MainParam(2),
                    Leadership = new MainParam(7),
                }
            },

            new Enemy
            {
                Name = "Chaos Ogres",
                TestListName = "5 Chaos Ogres (Beastmen)",
                Type = UnitType.Special,
                Size = 5,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(2),
                Attacks = new MainParam(3),
                Leadership = new MainParam(7),
                Armour = new MainParam(6),
                Fear = true,
            },

             new Enemy
            {
                Name = "Plague Monks",
                TestListName = "20 Plague Monks (Skaven)",
                Type = UnitType.Special,
                Size = 20,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(3),
                Leadership = new MainParam(5),
                Frenzy = true,
                StrengthInNumbers = true,
            },

            new Enemy
            {
                Name = "Tomb Guard",
                TestListName = "16 Tomb Guard (Tomb Kings)",
                Type = UnitType.Special,
                Size = 16,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(5),
                KillingBlow = true,
                Undead = true,
            },

            new Enemy
            {
                Name = "Grave Guard",
                TestListName = "16 Grave Guard (Vampire Counts)",
                Type = UnitType.Special,
                Size = 16,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(4),
                KillingBlow = true,
                Undead = true,
            },

            new Enemy
            {
                Name = "Greatswords",
                TestListName = "20 Greatswords (Empire)",
                Type = UnitType.Special,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(5),
                HitLast = true,
                Stubborn = true
            },

            new Enemy
            {
                Name = "Black Orcs",
                TestListName = "16 Black Orcs (Orcs&Goblins)",
                Type = UnitType.Special,
                Size = 16,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(5),
                HitLast = true
            },

            new Enemy
            {
                Name = "Orc Boar Boys",
                TestListName = "8 Orc Boar Boys (Orcs&Goblins)",
                Type = UnitType.Special,
                Size = 8,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(3),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(7),
                Armour = new MainParam(3),

                Mount = new Enemy
                {
                    Name = "Boar",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(3),
                }
            },

            new Enemy
            {
                Name = "Cold One Knights",
                TestListName = "8 Cold One Knights (Dark Elves)",
                Type = UnitType.Special,
                Size = 8,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(4),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(6),
                Attacks = new MainParam(1),
                Leadership = new MainParam(9),
                Armour = new MainParam(2),
                Hate = true,
                Fear = true,
                Lance = true,

                Mount = new Enemy
                {
                    Name = "Cold One",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(3),
                }
            },


            new Enemy
            {
                Name = "Cold One Cavalry",
                TestListName = "8 Cold One Cavalry (Lizardmen)",
                Type = UnitType.Special,
                Size = 8,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(2),
                ColdBlooded = true,
                Fear = true,

                Mount = new Enemy
                {
                    Name = "Cold One",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(3),
                }
            },

            new Enemy
            {
                Name = "Bloodletters",
                TestListName = "20 Bloodletters (Chaos)",
                Type = UnitType.Special,
                Size = 20,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(4),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(6),
                Frenzy = true
            },

            new Enemy
            {
                Name = "Sword Masters",
                TestListName = "16 Sword Masters of Hoeth (High Elves)",
                Type = UnitType.Special,
                Size = 16,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(5),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(5),
                HitFirst = true
            },

            new Enemy
            {
                Name = "Hammerers",
                TestListName = "16 Hammerers (Dwarfs)",
                Type = UnitType.Special,
                Size = 16,
                Movement = new MainParam(3),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(6),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(9),
                Armour = new MainParam(5),
                Stubborn = true,
            },
        };

        private static List<Enemy> EnemiesRareUnits = new List<Enemy>
        {
            new Enemy
            {
                Name = "Snotling Pump Wagon",
                TestListName = "Snotling Pump Wagon (Orcs&Goblins)",
                Type = UnitType.Rare,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(2),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(2),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(3),
                Attacks = new MainParam(5),
                Leadership = new MainParam(4),
                Unbreakable = true,
                Armour = new MainParam(6),
            },

            new Enemy
            {
                Name = "Flagellants",
                TestListName = "24 Flagellant Warband (The Empire)",
                Type = UnitType.Rare,
                Size = 24,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(2),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(3),
                Attacks = new MainParam(1),
                Leadership = new MainParam(10),
                Unbreakable = true,
                Frenzy = true,
                Flail = true,
            },

            new Enemy
            {
                Name = "Waywathers",
                TestListName = "16 Waywathers (Wood Elves)",
                Type = UnitType.Rare,
                Size = 16,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(3),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                HitFirst = true
            },

            new Enemy
            {
                Name = "White Lions",
                TestListName = "16 White Lions (High Elves)",
                Type = UnitType.Rare,
                Size = 16,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(6),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(1),
                Leadership = new MainParam(8),
                Armour = new MainParam(6),
                HitFirst = true
            },

            new Enemy
            {
                Name = "Black Guard",
                TestListName = "16 Black Guard (Dark Elves)",
                Type = UnitType.Rare,
                Size = 16,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(4),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(6),
                Attacks = new MainParam(1),
                Leadership = new MainParam(9),
                Armour = new MainParam(5),
                Hate = true,
                Stubborn = true,
            },

            new Enemy
            {
                Name = "Troll Slayers",
                TestListName = "16 Troll Slayers (Dwarfs)",
                Type = UnitType.Rare,
                Size = 16,
                Movement = new MainParam(3),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(2),
                Attacks = new MainParam(1),
                Leadership = new MainParam(10),
                Unbreakable = true,
            },

            new Enemy
            {
                Name = "Grail Knights",
                TestListName = "12 Grail Knights (Bretonnia)",
                Type = UnitType.Rare,
                Size = 12,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(3),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(2),
                Ward = new MainParam(5),
                Lance = true,

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Warhorse",
                    Size = 12,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                }
            },

            new Enemy
            {
                Name = "Blood Knights",
                TestListName = "6 Blood Knights (Vampire Counts)",
                Type = UnitType.Rare,
                Size = 6,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(4),
                Attacks = new MainParam(2),
                Leadership = new MainParam(7),
                Armour = new MainParam(2),
                Ward = new MainParam(5),
                Frenzy = true,
                Undead = true,
                Lance = true,

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Nightmare",
                    Size = 6,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(3),
                }
            },

            new Enemy
            {
                Name = "Skullcrushers",
                TestListName = "6 Skullcrushers of Khorne (Chaos)",
                Type = UnitType.Rare,
                Size = 6,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(1),
                Initiative = new MainParam(5),
                Attacks = new MainParam(2),
                Leadership = new MainParam(8),
                Armour = new MainParam(1),
                Fear = true,

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Juggernaut",
                    Size = 6,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(5),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(5),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(3),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(3),
                    Leadership = new MainParam(7),
                }
            },
        };

        private static List<Enemy> EnemiesHeroes = new List<Enemy>
        {
            new Enemy
            {
                Name = "Tretch Craventail",
                TestListName = "Tretch Craventail (Skaven)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(6),
                Attacks = new MainParam(4),
                Leadership = new MainParam(6),
                Armour = new MainParam(5),
                Ward = new MainParam(4),
            },

            new Enemy
            {
                Name = "The Herald Nekaph",
                TestListName = "The Herald Nekaph (Tomb Kings)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(3),
                Attacks = new MainParam(3),
                Leadership = new MainParam(8),
                Ward = new MainParam(5),
                KillingBlow = true,
                Undead = true,
                Flail = true,
                MultiWounds = "2",
            },

            new Enemy
            {
                Name = "Gitilla",
                TestListName = "Gitilla da Hunter (Orcs&Goblins)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(4),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(4),
                Attacks = new MainParam(3),
                Leadership = new MainParam(7),
                Armour = new MainParam(3),

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Ulda the Great Wolf",
                    Size = 1,
                    Movement = new MainParam(9),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(2),
                    Leadership = new MainParam(3),
                }
            },

            new Enemy
            {
                Name = "Moonclaw",
                TestListName = "Moonclaw, Son of Murrslieb (Beastmen)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(3),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(3),
                Attacks = new MainParam(3),
                Leadership = new MainParam(7),
                Ward = new MainParam(5),

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Umbralok",
                    Size = 1,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(3),
                    Leadership = new MainParam(6),
                }
            },

            new Enemy
            {
                Name = "Ludwig Schwarzhelm",
                TestListName = "Ludwig Schwarzhelm (The Empire)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(5),
                Attacks = new MainParam(3),
                Leadership = new MainParam(8),
                Armour = new MainParam(2),
                KillingBlow = true,
                Reroll = "ToWound",

                Mount = new Enemy
                {
                    Type = UnitType.Mount,
                    Name = "Warhorse",
                    Size = 1,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                }
            },

            new Enemy
            {
                Name = "Gor-Rok",
                TestListName = "Gor-Rok, The Great White Lizard (Lizardmen)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(2),
                Initiative = new MainParam(3),
                Attacks = new MainParam(4),
                Leadership = new MainParam(8),
                ColdBlooded = true,
                Armour = new MainParam(3),
                Stubborn = true,
                NoKollingBlow = true,
                Reroll = "ToHit;OpponentToWound",
            },

            new Enemy
            {
                Name = "Josef Bugman",
                TestListName = "Josef Bugman Master Brewer (Dwarfs)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(3),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(2),
                Initiative = new MainParam(4),
                Attacks = new MainParam(4),
                Leadership = new MainParam(10),
                Armour = new MainParam(3),
                Ward = new MainParam(4),
                ImmuneToPsychology = true,
            },

            new Enemy
            {
                Name = "Drycha",
                TestListName = "Drycha (Wood Elves)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(8),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                Terror = true,
                Reroll = "ToHit",
            },

            new Enemy
            {
                Name = "Caradryan",
                TestListName = "Caradryan, Capitain ot The Phoenix Guard (High Elves)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(6),
                Strength = new MainParam(4),
                Toughness = new MainParam(3),
                Wounds = new MainParam(2),
                Initiative = new MainParam(7),
                Attacks = new MainParam(3),
                Leadership = new MainParam(9),
                Armour = new MainParam(5),
                Ward = new MainParam(4),
                Fear = true,
                HitFirst = true,
                MultiWounds = "D3",
            },

            new Enemy
            {
                Name = "Konrad",
                TestListName = "Konrad Von Carstein (Vampire Counts)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(6),
                Attacks = new MainParam(4),
                Leadership = new MainParam(6),
                Armour = new MainParam(5),
                Fear = true,
                HitFirst = true,
                Reroll = "ToHit",
                MultiWounds = "2",
                Undead = true,
            },

            new Enemy
            {
                Name = "Throgg",
                TestListName = "Throgg, King of Trolls (Chaos)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(2),
                Strength = new MainParam(6),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(2),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                Fear = true,
                Regeneration = true,
                LargeBase = true,
            },

            new Enemy
            {
                Name = "Malus Darkblade (Tz'arkan)",
                TestListName = "Malus Darkblade in Tz'arkan state (Dark Elves)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(2),
                Initiative = new MainParam(9),
                Attacks = new MainParam(3),
                Leadership = new MainParam(10),
                Armour = new MainParam(3),
                Reroll = "ToWound",
                NoArmour = true,

                Mount = new Enemy
                {
                    Name = "Spite",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(2),
                    Leadership = new MainParam(4),
                    Armour = new MainParam(5),
                    Fear = true,
                }
            },

            new Enemy
            {
                Name = "Deathmaster Snikch",
                TestListName = "Deathmaster Snikch (Skaven)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(8),
                BallisticSkill = new MainParam(6),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(2),
                Initiative = new MainParam(10),
                Attacks = new MainParam(6),
                Leadership = new MainParam(8),
                Ward = new MainParam(4),
                HitFirst = true,
                ArmourPiercing = 2,
                MultiWounds = "D3",
            },

            new Enemy
            {
                Name = "Chakax",
                TestListName = "Chakax, The Eternity Warden (Lizardmen)",
                Type = UnitType.Hero,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(7),
                Toughness = new MainParam(5),
                Wounds = new MainParam(2),
                Initiative = new MainParam(3),
                Attacks = new MainParam(4),
                Leadership = new MainParam(8),
                ColdBlooded = true,
                Armour = new MainParam(4),
                Ward = new MainParam(5),
                Unbreakable = true,
                HitFirst = true,
                Reroll = "ToHit",
            },
        };

        private static List<Enemy> EnemiesLords = new List<Enemy>
        {
            new Enemy
            {
                Name = "Green Knight",
                TestListName = "Green Knight (Bretonnia)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(6),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(6),
                Attacks = new MainParam(4),
                Leadership = new MainParam(9),
                Ward = new MainParam(5),
                ImmuneToPsychology = true,
                Terror = true,
                Undead = true,

                Mount = new Enemy
                {
                    Name = "Shadow Steed",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(4),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(4),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                    Armour = new MainParam(5),
                }
            },

            new Enemy
            {
                Name = "Khuzrak",
                TestListName = "Khuzrak, The One-eye (Beastmen)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(1),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(5),
                Attacks = new MainParam(4),
                Leadership = new MainParam(9),
                Armour = new MainParam(2),
            },


            new Enemy
            {
                Name = "Khalida",
                TestListName = "High Queen Khalida, Beloved of Asaph (Tomb Kings)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(9),
                Attacks = new MainParam(5),
                Leadership = new MainParam(10),
                HitFirst = true,
                Undead = true,
                PoisonAttack = true,
            },

            new Enemy
            {
                Name = "Louen Leoncoeur",
                TestListName = "Louen Leoncoeur, The Lionhearted (Bretonnia)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(5),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(7),
                Attacks = new MainParam(5),
                Leadership = new MainParam(9),
                Armour = new MainParam(3),
                Ward = new MainParam(5),
                Lance = true,
                ImmuneToPsychology = true,
                Regeneration = true,
                Reroll = "ToHit;ToWound",

                Mount = new Enemy
                {
                    Name = "Beaquis",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(5),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(5),
                    Toughness = new MainParam(5),
                    Wounds = new MainParam(4),
                    Initiative = new MainParam(6),
                    Attacks = new MainParam(4),
                    Leadership = new MainParam(9),
                    Armour = new MainParam(5),
                    Terror = true,
                }
            },

            new Enemy
            {
                Name = "Kurt Helborg",
                TestListName = "Kurt Helborg (The Empire)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(6),
                Attacks = new MainParam(4),
                Leadership = new MainParam(9),
                Armour = new MainParam(2),
                Stubborn = true,
                ImmuneToPsychology = true,
                AutoWound = true,
                NoArmour = true,

                Mount = new Enemy
                {
                    Name = "Warhorse",
                    Type = UnitType.Mount,
                    Size = 8,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(3),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(5),
                }
            },

            new Enemy
            {
                Name = "Zacharias",
                TestListName = "Zacharias The Everliving (Vampire Counts)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(6),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(8),
                Attacks = new MainParam(5),
                Leadership = new MainParam(10),
                Ward = new MainParam(4),
                Undead = true,

                Mount = new Enemy
                {
                    Name = "Zombie Dragon",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(6),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(6),
                    Toughness = new MainParam(6),
                    Wounds = new MainParam(6),
                    Initiative = new MainParam(1),
                    Attacks = new MainParam(4),
                    Leadership = new MainParam(4),
                    Armour = new MainParam(5),
                    Terror = true,
                    Undead = true,
                }
            },

            new Enemy
            {
                Name = "Karl Franz",
                TestListName = "The Emperor Karl Franz (The Empire)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(4),
                Toughness = new MainParam(4),
                Wounds = new MainParam(3),
                Initiative = new MainParam(6),
                Attacks = new MainParam(4),
                Leadership = new MainParam(10),
                Armour = new MainParam(4),
                Ward = new MainParam(4),
                AutoWound = true,
                NoArmour = true,
                MultiWounds = "D3",

                Mount = new Enemy
                {
                    Name = "Deathclaw",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(6),
                    WeaponSkill = new MainParam(6),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(5),
                    Toughness = new MainParam(5),
                    Wounds = new MainParam(4),
                    Initiative = new MainParam(5),
                    Attacks = new MainParam(4),
                    Leadership = new MainParam(8),
                    Terror = true,
                }
            },

            new Enemy
            {
                Name = "Tyrion",
                TestListName = "Tyrion, The Defender of Ulthuan (High Elves)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(5),
                WeaponSkill = new MainParam(9),
                BallisticSkill = new MainParam(7),
                Strength = new MainParam(7),
                Toughness = new MainParam(3),
                Wounds = new MainParam(4),
                Initiative = new MainParam(10),
                Attacks = new MainParam(4),
                Leadership = new MainParam(10),
                HitFirst = true,
                Armour = new MainParam(1),
                Ward = new MainParam(4),
                Regeneration = true,

                Mount = new Enemy
                {
                    Name = "Malhandir",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(10),
                    WeaponSkill = new MainParam(4),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(3),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(5),
                    Attacks = new MainParam(2),
                    Leadership = new MainParam(7),
                }
            },

            new Enemy
            {
                Name = "Torgrim Grudgebearer",
                TestListName = "Torgrim Grudgebearer (Dwarfs)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(3),
                WeaponSkill = new MainParam(7),
                BallisticSkill = new MainParam(6),
                Strength = new MainParam(4),
                Toughness = new MainParam(5),
                Wounds = new MainParam(7),
                Initiative = new MainParam(4),
                Attacks = new MainParam(4),
                Leadership = new MainParam(10),
                Armour = new MainParam(2),
                Ward = new MainParam(4),
                HitFirst = true,
                ImmuneToPsychology = true,
                Stubborn = true,

                Mount = new Enemy
                {
                    Name = "Thronebearers",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(3),
                    WeaponSkill = new MainParam(5),
                    BallisticSkill = new MainParam(3),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(0),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(4),
                    Leadership = new MainParam(0),
                }
            },

            new Enemy
            {
                Name = "Orion",
                TestListName = "Orion, The King in the Wood (Wood Elves)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(9),
                WeaponSkill = new MainParam(8),
                BallisticSkill = new MainParam(8),
                Strength = new MainParam(6),
                Toughness = new MainParam(5),
                Wounds = new MainParam(5),
                Initiative = new MainParam(9),
                Attacks = new MainParam(5),
                Leadership = new MainParam(10),
                HitFirst = true,
                Frenzy = true,
                Terror = true,
                Unbreakable = true,
                Ward = new MainParam(5),

                Mount = new Enemy
                {
                    Name = "Hound of Orion",
                    Type = UnitType.Hero,
                    Size = 2,
                    Movement = new MainParam(9),
                    WeaponSkill = new MainParam(4),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(4),
                    Toughness = new MainParam(4),
                    Wounds = new MainParam(1),
                    Initiative = new MainParam(4),
                    Attacks = new MainParam(1),
                    Leadership = new MainParam(6),
                    Frenzy = true,
                    Unbreakable = true,
                }
            },

            new Enemy
            {
                Name = "Vermin Lord",
                TestListName = "Vermin Lord (Skaven)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(8),
                WeaponSkill = new MainParam(8),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(6),
                Toughness = new MainParam(5),
                Wounds = new MainParam(5),
                Initiative = new MainParam(10),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                Ward = new MainParam(5),
                ImmuneToPsychology = true,
                Terror = true,
                MultiWounds = "D3",
            },


            new Enemy
            {
                Name = "Malekith",
                TestListName = "Malekith, Witch King of Naggaroth (Dark Elves)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(8),
                WeaponSkill = new MainParam(5),
                BallisticSkill = new MainParam(4),
                Strength = new MainParam(6),
                Toughness = new MainParam(3),
                Wounds = new MainParam(3),
                Initiative = new MainParam(8),
                Attacks = new MainParam(4),
                Leadership = new MainParam(10),
                NoArmour = true,
                Armour = new MainParam(4),
                Ward = new MainParam(2),

                Mount = new Enemy
                {
                    Name = "Seraphon",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(6),
                    WeaponSkill = new MainParam(6),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(6),
                    Toughness = new MainParam(6),
                    Wounds = new MainParam(6),
                    Initiative = new MainParam(4),
                    Attacks = new MainParam(5),
                    Leadership = new MainParam(8),
                    Armour = new MainParam(3),
                    Terror = true,
                }
            },

            new Enemy
            {
                Name = "Kroq-Gar",
                TestListName = "Kroq-Gar Ancient (Lizardmen)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(6),
                BallisticSkill = new MainParam(3),
                Strength = new MainParam(6),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(4),
                Attacks = new MainParam(5),
                Leadership = new MainParam(8),
                ColdBlooded = true,
                Armour = new MainParam(3),
                Ward = new MainParam(5),
                MultiWounds = "2",

                Mount = new Enemy
                {
                    Name = "Grymloq",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(7),
                    WeaponSkill = new MainParam(3),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(7),
                    Toughness = new MainParam(5),
                    Wounds = new MainParam(5),
                    Initiative = new MainParam(2),
                    Attacks = new MainParam(5),
                    Leadership = new MainParam(5),
                    Armour = new MainParam(4),
                    Terror = true,
                    ColdBlooded = true,
                    MultiWounds = "D3",
                    LargeBase = true,
                }
            },

            new Enemy
            {
                Name = "Archaon",
                TestListName = "Archaon, Lord of the End Times (Chaos)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(9),
                BallisticSkill = new MainParam(5),
                Strength = new MainParam(5),
                Toughness = new MainParam(5),
                Wounds = new MainParam(4),
                Initiative = new MainParam(7),
                Attacks = new MainParam(10),
                Leadership = new MainParam(10),
                Armour = new MainParam(1),
                Ward = new MainParam(3),
                ImmuneToPsychology = true,
                NoArmour = true,
                Terror = true,

                Mount = new Enemy
                {
                    Name = "Dorghar",
                    Type = UnitType.Mount,
                    Size = 1,
                    Movement = new MainParam(8),
                    WeaponSkill = new MainParam(4),
                    BallisticSkill = new MainParam(0),
                    Strength = new MainParam(5),
                    Toughness = new MainParam(5),
                    Wounds = new MainParam(3),
                    Initiative = new MainParam(3),
                    Attacks = new MainParam(3),
                    Leadership = new MainParam(9),
                    Armour = new MainParam(4),
                    LargeBase = true,
                }
            },

            new Enemy
            {
                Name = "Grimgor Ironhide",
                TestListName = "Grimgor Ironhide (Orcs&Goblins)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(4),
                WeaponSkill = new MainParam(8),
                BallisticSkill = new MainParam(1),
                Strength = new MainParam(7),
                Toughness = new MainParam(5),
                Wounds = new MainParam(3),
                Initiative = new MainParam(5),
                Attacks = new MainParam(7),
                Leadership = new MainParam(9),
                Armour = new MainParam(1),
                Ward = new MainParam(5),
                Hate = true,
                HitFirst = true,
                ImmuneToPsychology = true,
            },

            new Enemy
            {
                Name = "Bloodthister",
                TestListName = "Greater Daemon Bloodthister (Chaos)",
                Type = UnitType.Lord,
                Size = 1,
                Movement = new MainParam(6),
                WeaponSkill = new MainParam(10),
                BallisticSkill = new MainParam(0),
                Strength = new MainParam(7),
                Toughness = new MainParam(6),
                Wounds = new MainParam(7),
                Initiative = new MainParam(10),
                Attacks = new MainParam(7),
                Leadership = new MainParam(9),
                Armour = new MainParam(4),
                Ward = new MainParam(5),
                Terror = true,
                KillingBlow = true,
                LargeBase = true,
            },
        };
    }
}
